apiVersion: v1
kind: ConfigMap
metadata:
  name: django-pro-configmap-cv
  namespace: prod
  labels:
    app: django-pro
    env: prod
data:
  DEBUG: "False"
  FLASK_APP: "run.py"
  FLASK_DEBUG: "False"
  SERVER_ADDRESS: "http://localhost:5005/"
