apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret-cv-25-03-2026
  namespace: dev
  labels:
    app: ecommerce
    env: dev
type: Opaque
stringData:
  STRIPE_SECRET_KEY: "sk_test_VOTRE_CLE_SECRETE_ICI"
  STRIPE_PUBLISHABLE_KEY: "pk_test_VOTRE_CLE_PUBLIQUE_ICI"
